import React, { useState } from "react";
import Head from "next/head";
import { Toaster } from "react-hot-toast";
import Login from "./modals/LoginModel";
import Register from "./modals/RegisterModel";
import { BiUser } from "react-icons/bi";
import useLoginModal from "../hooks/useLoginModal";
import { useSession } from "next-auth/react";
import LoadingModel from "./modals/LoadingModel";

const Layout = ({ children }) => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://api.mapbox.com/mapbox-gl-js/v2.8.1/mapbox-gl.css"
          rel="stylesheet"
        />
      </Head>
      <div className="relative bg-slate-400 h-screen w-screen overflow-hidden">
        <Toaster />
        <LoadingModel />
        <Login />
        <Register />
        {children}
        {/* {!session?.user && (
          <div className="absolute top-2 right-10 cursor-pointer rounded-full p-2 bg-darkbg text-lightestSlate">
            <BiUser size={30} onClick={() => onOpen()} />
          </div>
        )} */}
      </div>
    </div>
  );
};

export default Layout;
